# -*- coding: utf-8 -*-
"""demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_xBDEPeSJk2eAvoGlNhYfefQLN-lHLKo
"""

from simulation import Simulation

sim = Simulation(
    num_subscribers=1000,
    total_years=20,
    visualize=True
)

sim.run_full_simulation()