# -*- coding: utf-8 -*-
"""GOVERNMENT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1veL0knn5jLQhcMDPU9PeIG2T44fb_wzG
"""

import numpy as np
import random

class Government:
  def __init__(self, num_lots_range=(2,4), reserve_price_range = (int(2.12e10), int(2.62e10)),
               licenses = None,
               bid_increment = 0.05, deposit_rate = 0.25, coverage_obligation_5g = 125000,
               hhi_threshold = 5000, fine_amount_range = (300000, 500000),
               inspection_frequency = 0.3, speed_limit = None, subsidy_amount_range = (int(5e8), np.intc(7e8))):
    self.num_lots_range = num_lots_range
    self.reserve_price_range = reserve_price_range
    self.licenses = licenses
    self.bid_increment = bid_increment
    self.deposit_rate = deposit_rate
    self.coverage_obligation_5g = coverage_obligation_5g
    self.hhi_threshold = hhi_threshold
    self.fine_amount = random.randint(*fine_amount_range)
    self.inspection_frequency = inspection_frequency
    self.speed_limit = speed_limit
    self.subsidy_amount = random.randint(*subsidy_amount_range)
    self.forecasted_npv = 0

  def create_5g_licenses(self):
    num_lots = random.randint(*self.num_lots_range)
    licenses = []
    for lot_id in range(num_lots):
        reserve_price = random.uniform(*self.reserve_price_range)
        bid_step = reserve_price * self.bid_increment
        deposit = reserve_price * self.deposit_rate
        licenses.append({
            "lot_id": lot_id,
            "reserve_price": reserve_price,
            "current_price": reserve_price,
            "bid_step": bid_step,
            "deposit": deposit
        })
    self.licenses = licenses
    return licenses

  def inspect_prices(self, operators, equilibrium_prices):
    fined = []
    fines = {}
    if random.random() < self.inspection_frequency:
      for op in operators:
        if op.has_5g_license:
          for t in op.tariffs_5g:
            eq_price = equilibrium_prices.get(op.id, t.price)
            if abs(t.price - eq_price) > 1e-6:
              fined.append(op.id)
              op.fine_price += self.fine_amount
              op.fine_amount += op.fine_price
              t.price = eq_price
              op.profit_5g -= op.fine_price
              fines[op.id] = op.fine_amount
    return fined, fines

  def check_hhi(self, hhi, market_shares, operators):
    if hhi > self.hhi_threshold:
      dominant_idx = np.argmax(market_shares)
      dominant_op = operators[dominant_idx]
      fine_hhi = self.fine_amount
      dominant_op.fine_hhi += fine_hhi
      dominant_op.fine_amount += fine_hhi
      dominant_op.profit_5g -= fine_hhi
      return dominant_op.fine_amount, hhi
    return 0, hhi

  def enforce_coverage(self, operators, year, license_period = 20):
    if year == license_period:
      for op in operators:
        if op.has_5g_license:
          if op.base_stations_per_km2_5g < (self.coverage_obligation_5g * 1.1e-5):
            gap = (self.coverage_obligation_5g * 1.1e-5) - op.base_stations_per_km2_5g
            if gap != 0:
              fine_coverage = self.fine_amount
              op.fine_coverage += fine_coverage
              op.fine_amount += fine_coverage
              op.profit_5g -= fine_coverage
      return op.fine_amount