# -*- coding: utf-8 -*-
"""OPERATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13LsrIy6bBx94URP0sJya4lDvRqxsp4R5
"""

import numpy as np
import random
from scipy.stats import norm

class Operator:
  def __init__(self, op_id, name, tariffs_4g = None, tariffs_5g = None, q_4g = 0, q_5g = 0, revenue_4g = 0, revenue_5g = 0,
               fixed_4g_range = (int(1e10), int(6e10)), variable_4g_range = (100, 600),
               fixed_5g = 0, variable_5g = 0, cumulative_capex_5g = 0,
               profit_4g = 0, profit_5g = 0, cumulative_profit_5g = 0,
               license_remaining_years_4g = None, participation_auction = False, has_5g_license = False,
               gov_subsidy = 0,
               base_stations_per_km2_5g = 0, station_cost = 2000000, quality = None, ecosystem = None,
               volatility = 0.0, vendor = 'none', fine_amount = 0, investment_budget = 0):
    self.id = op_id
    self.name = name
    self.tariffs_4g = tariffs_4g if tariffs_4g else []
    self.tariffs_5g = tariffs_5g if tariffs_5g else []
    self.q_4g = q_4g
    self.total_q_4g = 0
    self.q_5g = q_5g
    self.total_q_5g = q_5g
    self.revenue_4g = revenue_4g
    self.cumulative_revenue_4g_old = 0
    self.cumulative_revenue_4g = 0
    self.revenue_5g = revenue_5g
    self.cumulative_revenue_5g = 0
    self.fixed_4g = random.uniform(*fixed_4g_range)
    self.variable_4g = random.uniform(*variable_4g_range)
    self.costs_4g = 0
    self.cumulative_costs_4g = 0
    self.fixed_5g = random.uniform(int(2e10), int(1.2e11))
    self.cumulative_costs_4g_old = 0
    self.variable_5g = random.randint(500, 1500)
    self.costs_5g = 0
    self.cumulative_costs_5g = 0
    self.cumulative_capex_5g = cumulative_capex_5g
    self.annual_capex_5g = 0
    self.profit_4g = profit_4g
    self.profit_5g = profit_5g
    self.discount_rate = 0.1
    self.cumulative_profit_4g = 0
    self.cumulative_profit_4g_old = 0
    self.cumulative_profit_5g = cumulative_profit_5g
    self.invest_profit = 0
    if license_remaining_years_4g is None:
      self.license_remaining_years_4g = random.randint(0,16)
    self.participation_auction = participation_auction
    self.has_5g_license = has_5g_license
    self.gov_subsidy = gov_subsidy
    self.base_stations_per_km2_5g = base_stations_per_km2_5g
    self.base_stations_per_km2_5g_per_year = 0
    self.station_cost = station_cost
    if quality is None:
      self.quality = np.random.uniform(0.7, 1.0)
    if ecosystem is None:
      self.ecosystem = np.random.uniform(0.7, 1.0)
    self.volatility = volatility
    self.vendor = vendor
    self.arpu = 0
    self.subscribers = []
    self.market_share = 0
    self.fine_amount = fine_amount
    self.fine_hhi = 0
    self.fine_coverage = 0
    self.fine_price = 0
    self.investment_budget = investment_budget
    self.forecasted_npv = 0
    self.sharing_factor = 1.0
    self.entry_year_5g = None
    self.waiting_for_entry = False
    self.activated_5g = False

  def cost_function(self, q, technology):
    if technology == '4G':
      fixed = self.fixed_4g
      variable = self.variable_4g * q
    else:
      fixed = self.fixed_5g
      variable = self.variable_5g * q
    fixed = max(0, fixed - self.gov_subsidy)
    return fixed + variable

  def create_tariffs(self, year, speed_limit = None):
    if year == 1:
      speed_4g = random.uniform(30, 80)
      price_4g = random.uniform(400, 1500)
      if speed_limit is not None:
        speed_4g = min(speed_4g, speed_limit)
      tariff_4g = Tariff(tariff_id = len(self.tariffs_4g), operator_id = self.id,
                       technology = '4G', speed = speed_4g, price = price_4g)
      self.tariffs_4g.append(tariff_4g)

    else:
      if self.has_5g_license:
        speed_5g = random.uniform(300, 800)
        price_5g = 0
        if speed_limit is not None:
          speed_5g = min(speed_5g, speed_limit)
        tariff_5g = Tariff(tariff_id = len(self.tariffs_5g), operator_id = self.id,
                         technology = '5G', speed = speed_5g, price = price_5g)
        self.tariffs_5g.append(tariff_5g)

  def calculate_valuations(self, lots):
    valuations = {}
    for lot in lots:
      step = random.randint(1, 10)
      valuation = lot['deposit'] + lot['current_price'] + step * lot['bid_step']
      valuations[lot['lot_id']] = valuation
    return valuations

  def coverage(self):
    if self.has_5g_license:
      return self.base_stations_per_km2_5g
    return 0.0

  def build_5g_stations(self):
    self.annual_capex_5g = 0
    if self.has_5g_license:
      investment_budget = max(self.profit_4g + self.profit_5g, 0)
      max_build = 10000
      built = min(max_build, int(investment_budget//self.station_cost))
      total_cost = built * self.station_cost * self.sharing_factor
      self.annual_capex_5g += total_cost
      self.base_stations_per_km2_5g_per_year = built * 1.1e-5
      self.base_stations_per_km2_5g += built * 1.1e-5
      if self.vendor == 'domestic':
        self.base_stations_per_km2_5g *= 0.85

  def generate_volatility(self):
    r = random.random()
    if r < 0.5:
      self.volatility = random.uniform(0, 0.3)
      return self.volatility
    elif r < 0.8:
      self.volatility = random.uniform(0.3, 0.7)
      return self.volatility
    else:
      self.volatility = random.uniform(0.7, 1.0)
      return self.volatility

  def evaluate_investment(self, S0, K, T_max, delay_yield = None):
    cash_flows = []
    T = 20
    for t in range(1, T + 1):
      expected_cf = S0 * (1.05**t)
      cash_flows.append(expected_cf)
    NPV = -K
    for t, cf in enumerate(cash_flows, start = 1):
      NPV += cf/(1 + self.discount_rate) ** t
    best_NPV_option = NPV
    best_T = 0
    if NPV >= 0:
      self.participation_auction = True
      return NPV, 0
    if K <= 0:
      K = 1e-6
    if self.license_remaining_years_4g < 10:
      best_NPV_option = -np.inf
      best_T = 0

      if delay_yield is None:
        delay_yield = 1.0 / T_max

      for T in np.arange(1, T_max + 1):
        self.generate_volatility()
        if T == 1:
          risk_free_rate = 0.1281
        elif T == 2:
          risk_free_rate = 0.1315
        elif T == 3 or T == 4:
          risk_free_rate = 0.136
        elif T == 5 or T == 6:
          risk_free_rate = 0.1425
        elif T in (7, 8, 9):
          risk_free_rate = 0.1458
        elif T == 10:
          risk_free_rate = 0.1476

        d1 = (np.log(S0 / K) + (risk_free_rate - delay_yield + 0.5 * self.volatility**2)*T)/(self.volatility*np.sqrt(T))
        d2 = d1 - self.volatility * np.sqrt(T)

        C_call = S0 * np.exp(-delay_yield * T) * norm.cdf(d1)-K * np.exp(-risk_free_rate*T)*norm.cdf(d2)
        NPV_option = (S0 - K) + C_call

        if NPV_option > best_NPV_option:
          best_NPV_option = NPV_option
          best_T = T
    self.participation_auction = True
    return best_NPV_option, best_T

  def calculate_arpu(self, revenue, q):
    if self.q_5g == 0:
      return 0
    self.arpu = self.revenue_5g / self.q_5g
    return self.arpu

  def calculate_market_share(self, total_market_size):
    own_size = sum(sub.weight for sub in self.subscribers)
    if total_market_size == 0:
      self.market_share = 0
    else:
      self.market_share = (own_size/total_market_size)
    return self.market_share

class Tariff:
  def __init__(self, tariff_id, operator_id, technology, speed, price):
    self.id = tariff_id
    self.operator_id = operator_id
    self.technology = technology
    self.speed = speed
    self.price = price

