# -*- coding: utf-8 -*-
"""simulation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AwYuzNE5qIStySYweQJziMkv54iJTPDV
"""

import numpy as np
import random
import matplotlib.pyplot as plt
from agents.operator import Operator
from agents.subscriber import Subscriber
from agents.government import Government
from matplotlib.ticker import MaxNLocator

class Simulation:
  def __init__(self, num_subscribers, num_operators = 4, total_years = 20, rational_range = (0.3, 0.7),
               discount_rate = 0.1, risk_free_rate = 0, equipment_scenario = 'none',
               dishonest_operators = 'none', infrastructure_sharing = 'none',
               strict_coverage = 'none', subsidy_scenario = 'none',
               speed_limit_policy = 'none', visualize = True):
    self.num_subscribers = num_subscribers
    self.num_operators = num_operators
    self.total_years = total_years
    self.rational = random.uniform(*rational_range)
    self.discount_rate = discount_rate
    self.risk_free_rate = risk_free_rate
    self.equipment_scenario = equipment_scenario
    self.dishonest_operators = dishonest_operators
    self.infrastructure_sharing = infrastructure_sharing
    self.strict_coverage = strict_coverage
    self.subsidy_scenario = subsidy_scenario
    self.speed_limit_policy = speed_limit_policy
    self.current_year = 0
    self.operators = []
    self.subscribers = []
    self.government = Government()
    self.history = {'Годы': [], 'Операторы 5G':[], 'HHI': [], 'Цены': [], 'Доли': [],
                    'Доли рынка 5G': [], 'Годовая выручка 5G': [], 'Годовые продажи 5G':[],
                    'Годовые издержки 5G':[], 'Годовые капитальные издержки 5G':[], 'Годовая прибыль 5G':[],
                    'Выручка 4G': [], 'Выручка 5G': [], 'Издержки 4G': [],
                    'Издержки 5G': [], 'CAPEX 5G':[], 'Прибыль 4G': [], 'Прибыль 5G': [], 'Инвестиционная прибыль':[],
                    'Кол-во тарифов 5G': [], 'Продано тарифов 4G': [],
                    'Продано тарифов 5G': [], 'ARPU 5G': [], 'Покрытие 5G': [],
                    'Лимит скорости': [], 'Штрафы': [], 'Штрафы за непокрытие':[], 'Штрафы за высокую концентрацию на рынке':[],
                    'Штрафы за необоснованное ценообразование':[], 'Суммарные инвестиции 5G': []}
    self.visualize = visualize
    self.year_policy = random.randint(1, self.total_years)

  def initialize_market_4g(self):
    years_4g = 15
    vendors = ['foreign', 'foreign', 'domestic', 'domestic']
    random.shuffle(vendors)
    for i in range(self.num_operators):
      vendor = vendors[i]
      op = Operator(op_id=i, name=f"Operator_{i+1}", vendor=vendor)
      op.create_tariffs(year = 1)
      self.operators.append(op)

    num_rational = int(self.num_subscribers * self.rational)
    for i in range(self.num_subscribers):
      is_rational = (i < num_rational)
      init_op = random.choice(self.operators)
      init_tariff = random.choice(init_op.tariffs_4g)
      sub = Subscriber(sub_id = i, current_operator = init_op, current_tariff = init_tariff,
                       is_rational = is_rational)
      self.subscribers.append(sub)
    for op in self.operators:
      op.cumulative_revenue_4g = 0
      op.cumulative_costs_4g = 0
      op.cumulative_profit_4g = 0
    for year in range(1, years_4g + 1):
      for op in self.operators:
        annual_revenue = sum(sub.current_tariff.price * sub.weight * 12
                             for sub in self.subscribers if sub.current_operator == op)
        q_4g = sum(sub.weight for sub in self.subscribers
                   if sub.current_operator == op and sub.current_tariff.technology == '4G')
        annual_cost = op.cost_function(q_4g, '4G')
        op.cumulative_revenue_4g_old += annual_revenue
        op.cumulative_costs_4g_old += annual_cost
        op.cumulative_profit_4g_old += annual_revenue - annual_cost

  def announce_auction(self):
    self.government.create_5g_licenses()
    self.participants = []
    for op in self.operators:
      S0 = random.randint(int(1e10), int(5e10))
      K = random.randint(int(4e11), int(8e11))
      npv, best_T = op.evaluate_investment(S0, K, T_max = 10)
      op.forecasted_npv += npv
      if best_T > 0:
        op.entry_year_5g = best_T
        op.waiting_for_entry = True
      else:
        op.entry_year_5g = 1
      if op.participation_auction:
        lots = self.government.licenses
        num_lots = len(lots)
        desired_lots = random.randint(1, num_lots)
        selected_lots = random.sample(lots, desired_lots)
        valuations = {}
        active_lots = set()
        for selected_lot in selected_lots:
          op.investment_budget -= selected_lot['deposit']
          valuation_dict = op.calculate_valuations([selected_lot])
          valuations[selected_lot["lot_id"]] = valuation_dict[selected_lot['lot_id']]
          active_lots.add(selected_lot["lot_id"])
        if len(active_lots) > 0:
          self.participants.append({"operator": op,
                             "valuations": valuations,
                              "active_lots": active_lots
                             })
      else:
        op.has_5g_license = False

  def run_auction(self):
    if getattr(self, "auction_completed", False):
      return []
    participants = self.participants
    self.auction_completed = True
    winners = []

    for lot in self.government.licenses:
      active_bidders = []
      for p in participants:
        if lot["lot_id"] in p["active_lots"]:
          active_bidders.append(p)
      if len(active_bidders) == 0:
        continue
      current_price = lot['reserve_price']
      last_active_bidder = None
      while len(active_bidders) > 0:
        remaining_bidders = []
        for bidder in active_bidders:
          valuation = bidder['valuations'][lot["lot_id"]]
          if valuation >= current_price:
            remaining_bidders.append(bidder)
            last_active_bidder = bidder
        if len(remaining_bidders) == 0:
          break
        active_bidders = remaining_bidders
        current_price += lot["bid_step"]
      if last_active_bidder is not None:
        winner = last_active_bidder['operator']
        winner.has_5g_license = True
        winner.activated_5g = False
        winner.base_stations_per_km2_5g = 0.0
        winner.annual_capex_5g += current_price
        winner.investment_budget -= current_price
        winners.append({
            "lot_id": lot["lot_id"],
            "operator_id": winner.id,
            "final_price": current_price
        })
    return winners

  def apply_yearly_policies(self, year):
    operators_5g = [op for op in self.operators if op.has_5g_license and op.activated_5g]
    if self.equipment_scenario != 'none' and year == self.year_policy:
      if self.equipment_scenario == 'domestic':
        for op in operators_5g:
          if op.vendor == 'domestic':
            continue
          op.vendor = 'domestic'
          op.station_cost *= 1.5
          op.variable_5g *= 1.1
          op.fixed_5g *= 1.3
          op.quality *= 0.6
      elif self.equipment_scenario == 'foreign':
        for op in operators_5g:
          if op.vendor == 'foreign':
            continue
          op.vendor = 'foreign'
          op.station_cost *= 1.1
          op.variable_5g *= 0.9
          op.quality *= 1.3

    if self.infrastructure_sharing != 'none' and year == self.year_policy and operators_5g:
      total_bs = sum(op.base_stations_per_km2_5g for op in operators_5g)
      for op in operators_5g:
        op.base_stations_per_km2_5g = total_bs / len(operators_5g)
        op.sharing_factor = 0.6

    if self.strict_coverage != 'none':
      required_per_year = (self.government.coverage_obligation_5g * 1.1e-5) / self.total_years
      for op in operators_5g:
          if op.base_stations_per_km2_5g_per_year < required_per_year:
            fine_annual_coverage = self.government.fine_amount
            op.fine_coverage += fine_annual_coverage
            op.fine_amount += fine_annual_coverage
            op.profit_5g -= fine_annual_coverage

    if self.subsidy_scenario != 'none' and year == 1:
      if self.subsidy_scenario == 'single':
        if operators_5g:
          best_op = max(operators_5g, key = lambda o: o.profit_4g)
          best_op.gov_subsidy = self.government.subsidy_amount
      elif self.subsidy_scenario == 'multiple':
        if len(operators_5g) > 1:
          sub_op = random.sample(operators_5g, random.randint(2, len(operators_5g)))
          for op in sub_op:
            op.gov_subsidy = self.government.subsidy_amount/len(sub_op)

    if self.speed_limit_policy != 'none':
      if year >= 8 and year <= 15:
        limit = max(20, 175 - (year - 5)*15)
        self.government.speed_limit = limit
      elif year > 15:
        self.government.speed_limit = 10
      else:
        self.government.speed_limit = None

  def equilibrium_prices(self, operators_5g):
    ops = [op for op in operators_5g]
    if not ops:
      return {}
    sorted_ops = sorted(ops, key = lambda op: op.variable_5g)
    market_remaining = 1.0
    operator_shares = {}
    active_operators = []
    excluded_operator = None
    for i, op in enumerate(sorted_ops):
      capacity = min(0.4, 0.1 + op.base_stations_per_km2_5g/100)
      assigned_share = min(capacity, market_remaining)
      operator_shares[op.id] = (assigned_share)
      active_operators.append(op)
      market_remaining -= assigned_share
      if market_remaining <= 0:
        if i + 1 < len(sorted_ops):
          excluded_operator = sorted_ops[i + 1]
        else:
          excluded_operator = op
        break
    if excluded_operator is None:
      equilibrium_price = sorted_ops[-1].variable_5g
    else:
      equilibrium_price = (excluded_operator.variable_5g)
    prices = {}
    for op in active_operators:
      prices[op.id] = equilibrium_price
    self.last_market_shares = (operator_shares)

    if self.dishonest_operators != 'none':
      for op in operators_5g:
        if random.random() < 0.4:
          deviation = random.uniform(-0.25, 0.40)
          prices[op.id] *= (1 + deviation)
    return prices


  def run_yearly_cycle(self, year):
    for op in self.operators:
      if op.has_5g_license and not op.activated_5g:
        if year >= op.entry_year_5g:
          op.activated_5g = True
          print(f"{op.name} запустил 5G в {year} год")
    operators_5g = [op for op in self.operators if op.has_5g_license and op.activated_5g]
    for op in operators_5g:
      op.build_5g_stations()
    if random.random() < 0.3:
      for op in operators_5g:
        num_new = random.randint(1, 4)
        for _ in range(num_new):
          op.create_tariffs(year)
    if operators_5g:
      eq_prices = self.equilibrium_prices(operators_5g)
      for op in operators_5g:
        for t in op.tariffs_5g:
          if t.technology == '5G':
            max_coverage = (self.government.coverage_obligation_5g * 1.1e-5)
            bonus = (0.1 * np.log1p(t.speed / 100)
            + 0.15 * (op.quality - 0.7)
            + 0.1 * op.ecosystem
            + 0.1 * (op.coverage()/ max_coverage))
            bonus = min(bonus, 0.5)
            t.price = int(eq_prices[op.id] * (1 + bonus))
    for sub in self.subscribers:
      available = []
      for op in self.operators:
        if op.license_remaining_years_4g > 0:
          for t in op.tariffs_4g:
            available.append(t)
        if op.has_5g_license and op.activated_5g:
          for t in op.tariffs_5g:
            available.append(t)
      best = sub.choose_tariff(available, self.operators, self.government.speed_limit, year)
      if best:
        sub.current_tariff = best
        sub.current_operator = next(o for o in self.operators if o.id == best.operator_id)

    for op in self.operators:
        op.subscribers = []
    for sub in self.subscribers:
        sub.current_operator.subscribers.append(sub)
    total_market_size = sum(sub.weight for sub in self.subscribers)
    total_market_size_5g = sum(sub.weight for sub in self.subscribers if sub.current_tariff.technology == '5G')
    total_revenue_market = 0
    sales = {}
    sales_5g = {}
    market_revenue_5g = 0
    market_q_5g = 0
    arpu_5g_list = []
    for op in self.operators:
      revenue_4g = 0
      revenue_5g = 0
      q_4g = 0
      q_5g = 0
      for sub in op.subscribers:
        tariff = sub.current_tariff
        if tariff.technology == "4G":
          revenue_4g += tariff.price * sub.weight * 12
          q_4g += sub.weight
        elif tariff.technology == "5G":
          revenue_5g += tariff.price * sub.weight * 12
          q_5g += sub.weight

      costs_4g = op.cost_function(q_4g, "4G")
      op.q_4g = q_4g
      op.total_q_4g += q_4g
      op.revenue_4g = revenue_4g
      op.cumulative_revenue_4g += revenue_4g
      op.costs_4g = costs_4g
      op.cumulative_costs_4g += costs_4g
      op.profit_4g = revenue_4g - costs_4g
      op.cumulative_profit_4g += op.profit_4g

      if op.has_5g_license and op.activated_5g:
        costs_5g = op.cost_function(q_5g, "5G")
        op.q_5g = q_5g
        op.total_q_5g += q_5g
        op.revenue_5g = revenue_5g
        op.cumulative_revenue_5g += revenue_5g
        op.costs_5g = costs_5g
        op.cumulative_costs_5g += op.costs_5g
        op.cumulative_capex_5g += op.annual_capex_5g
        op.profit_5g = revenue_5g - costs_5g
        op.cumulative_profit_5g += op.profit_5g
        op.invest_profit += op.profit_5g - op.annual_capex_5g
        market_revenue_5g += revenue_5g
        market_q_5g += q_5g
      else:
        op.q_5g = 0
        op.revenue_5g = 0
        op.costs_5g = 0
        op.profit_5g = 0
      op.total_revenue = op.revenue_4g + op.revenue_5g
      op.investment_budget += (
        op.profit_4g + op.profit_5g
    )
      op.investment_budget -= op.annual_capex_5g
      total_revenue_market += op.total_revenue
      sales[op.id] = op.q_4g + op.q_5g
      sales_5g[op.id] = op.q_5g
      if op.q_5g > 0:
        arpu = op.calculate_arpu(op.revenue_5g, op.q_5g)
      else:
        arpu = 0
      arpu_5g_list.append(arpu)


    shares = np.array([sales[op.id]/total_market_size for op in self.operators])*100
    if total_market_size_5g > 0:
      shares_5g = np.array([sales_5g[op.id]/total_market_size_5g for op in self.operators])*100
    else:
      shares_5g = np.zeros(len(self.operators))
    hhi = sum(s**2 for s in shares_5g)
    self.government.check_hhi(hhi, shares_5g, self.operators)
    self.apply_yearly_policies(year)
    self.government.inspect_prices(self.operators, eq_prices if operators_5g else {})

    self.history['Годы'].append(year)
    self.history['Операторы 5G'].append([op.name for op in self.operators if op.has_5g_license])
    self.history['HHI'].append(hhi)
    self.history['Цены'].append([[t.price for t in op.tariffs_5g] for op in self.operators])
    self.history['Доли'].append(shares)
    self.history['Доли рынка 5G'].append(shares_5g)
    self.history['Годовая выручка 5G'].append([op.revenue_5g for op in self.operators])
    self.history['Годовые продажи 5G'].append([op.q_5g for op in self.operators])
    self.history['Годовые издержки 5G'].append([op.costs_5g for op in self.operators])
    self.history['Годовые капитальные издержки 5G'].append([op.annual_capex_5g for op in self.operators])
    self.history['Годовая прибыль 5G'].append([op.profit_5g for op in self.operators])
    self.history['Выручка 4G'].append([op.cumulative_revenue_4g for op in self.operators])
    self.history['Выручка 5G'].append([op.cumulative_revenue_5g for op in self.operators])
    self.history['Издержки 4G'].append([op.cumulative_costs_4g for op in self.operators])
    self.history['Издержки 5G'].append([op.cumulative_costs_5g for op in self.operators])
    self.history['CAPEX 5G'].append([op.cumulative_capex_5g for op in self.operators])
    self.history['Прибыль 4G'].append([op.cumulative_profit_4g for op in self.operators])
    self.history['Прибыль 5G'].append([op.cumulative_profit_5g for op in self.operators])
    self.history['Инвестиционная прибыль'].append([op.invest_profit for op in self.operators])
    self.history['Кол-во тарифов 5G'].append([len(op.tariffs_5g) for op in self.operators])
    self.history['Продано тарифов 4G'].append([op.total_q_4g for op in self.operators])
    self.history['Продано тарифов 5G'].append([op.total_q_5g for op in self.operators])
    self.history['ARPU 5G'].append(arpu_5g_list)
    self.history['Покрытие 5G'].append([op.base_stations_per_km2_5g for op in self.operators])
    self.history['Лимит скорости'].append(self.government.speed_limit)
    self.history['Штрафы'].append([op.fine_amount for op in self.operators])
    self.history['Штрафы за непокрытие'].append([op.fine_coverage for op in self.operators])
    self.history['Штрафы за высокую концентрацию на рынке'].append([op.fine_hhi for op in self.operators])
    self.history['Штрафы за необоснованное ценообразование'].append([op.fine_price for op in self.operators])
    self.history['Суммарные инвестиции 5G'].append([op.investment_budget for op in self.operators])

  def compare_npv_vs_real(self):
    print("Сравнение прогнозного NPV и реального")
    for op in self.operators:
      if op.has_5g_license:
        print(f"{op.name}: прогнозный NPV = {op.forecasted_npv:.2f}, реальная прибыль от 5G: {op.invest_profit:.2f}")
      else:
        print(f"{op.name}: не вышел на рынок 5G")

  def run_full_simulation(self):
    print("Инициализация...")
    self.initialize_market_4g()
    print("Объявление аукциона...")
    self.announce_auction()
    print("Проведение аукциона...")
    self.run_auction()

    for year in range(1, self.total_years+1):
      self.current_year = year
      self.run_yearly_cycle(year)
    self.government.enforce_coverage(self.operators, self.total_years)
    self.compare_npv_vs_real()
    self.print_summary()
    if self.visualize:
      self.visualize_results()

  def print_summary(self):
    print("ИТОГИ СИМУЛЯЦИИ")
    print(f"Операторы 5G: {self.history['Операторы 5G'][-1]}")
    print(f"Доли операторов: {self.history['Доли'][-1]}")
    print(f"Доли операторов на рынке 5G: {self.history['Доли рынка 5G'][-1]}")
    print(f"Цены на тарифы 5G: {self.history['Цены'][-1]}")
    print(f"HHI: {self.history['HHI'][-1]}")
    print(f"Выручка 4G: {self.history['Выручка 4G'][-1]}")
    print(f"Выручка 5G: {self.history['Выручка 5G'][-1]}")
    print(f"Издержки 4G: {self.history['Издержки 4G'][-1]}")
    print(f"Издержки 5G: {self.history['Издержки 5G'][-1]}")
    print(f"Прибыль 4G: {self.history['Прибыль 4G'][-1]}")
    print(f"Прибыль 5G: {self.history['Прибыль 5G'][-1]}")
    print(f"Инвестиционная прибыль: {self.history['Инвестиционная прибыль'][-1]}")
    print(f"Количество тарифов 5G: {self.history['Кол-во тарифов 5G'][-1]}")
    print(f"Продано тарифов 4G: {self.history['Продано тарифов 4G'][-1]}")
    print(f"Продано тарифов 5G: {self.history['Продано тарифов 5G'][-1]}")
    print(f"ARPU 5G: {self.history['ARPU 5G'][-1]}")
    print(f"Покрытие 5G: {self.history['Покрытие 5G'][-1]}")
    print(f"Суммарные инвестиции 5G: {self.history['Суммарные инвестиции 5G'][-1]}")
    print(f"Штрафы: {self.history['Штрафы'][-1]}")
    print(f"Штрафы за непокрытие: {self.history['Штрафы за непокрытие'][-1]}")
    print(f"Штрафы за высокую концентрацию на рынке: {self.history['Штрафы за высокую концентрацию на рынке'][-1]}")
    print(f"Штрафы за необоснованное ценообразование: {self.history['Штрафы за необоснованное ценообразование'][-1]}")
  def visualize_results(self):
    years = self.history['Годы']
    fig, axes = plt.subplots(3, 3, figsize=(22, 14))
    fig.suptitle('Результаты симуляции рынка 5G', fontsize=20)
    #Доли рынка 5G
    labels = [f'Оператор {i+1}' for i in range(self.num_operators)]
    shares_5g = self.history['Доли рынка 5G'][-1]
    axes[0, 0].pie(
        shares_5g,
        labels=labels,
        autopct='%1.1f%%',
        startangle=90
    )
    axes[0, 0].set_title('Доли рынка операторов')

    #Цены 5G
    for i in range(self.num_operators):
      operator_prices = []
      for year_data in self.history['Цены']:
        tariffs = year_data[i]
        if len(tariffs) > 0:
          operator_prices.append(np.mean(tariffs))
        else:
          operator_prices.append(0)
      axes[0, 1].plot(
            years,
            operator_prices,
            linewidth=2,
            label=f'Оператор {i+1}'
        )
      axes[0, 1].set_title('Цены на тарифы 5G')
      axes[0, 1].set_xlabel('Год')
      axes[0, 1].set_ylabel('Цены, руб. ')
      axes[0, 1].legend()
      axes[0, 1].grid(True)

    #HHI
    axes[0, 2].plot(
        years,
        self.history['HHI'],
        linewidth=2,
        marker='o'
    )
    axes[0, 2].axhline(
        y=5000,
        linestyle='--',
        label='Порог HHI'
    )
    axes[0, 2].set_title('Индекс HHI')
    axes[0, 2].set_xlabel('Год')
    axes[0, 2].set_ylabel('HHI')
    axes[0, 2].legend()
    axes[0, 2].grid(True)

    #Прибыль
    profits_4g = np.array(self.history['Прибыль 4G'])
    profits_5g = np.array(self.history['Прибыль 5G'])
    for i, op in enumerate(self.operators):
        axes[1, 0].plot(
            years,
            profits_4g[:, i],
            linewidth=2,
            linestyle='--',
            label=f'{op.name} 4G'
        )
        axes[1, 0].plot(
            years,
            profits_5g[:, i],
            linewidth=2,
            label=f'{op.name} 5G'
        )

    axes[1, 0].set_title('Прибыль операторов')
    axes[1, 0].set_xlabel('Год')
    axes[1, 0].set_ylabel('Прибыль')
    axes[1, 0].legend(fontsize=8)
    axes[1, 0].grid(True)

    #Выручка
    revenue_4g = np.array(self.history['Выручка 4G'])
    revenue_5g = np.array(self.history['Выручка 5G'])
    for i, op in enumerate(self.operators):
        axes[1, 1].plot(
            years,
            revenue_4g[:, i],
            linestyle='--',
            linewidth=2,
            label=f'{op.name} 4G'
        )
        axes[1, 1].plot(
            years,
            revenue_5g[:, i],
            linewidth=2,
            label=f'{op.name} 5G'
        )
    axes[1, 1].set_title('Выручка операторов')
    axes[1, 1].set_xlabel('Год')
    axes[1, 1].set_ylabel('Выручка')
    axes[1, 1].legend(fontsize=8)
    axes[1, 1].grid(True)

    #Покрытие 5G
    coverage = np.array(self.history['Покрытие 5G'])
    for i in range(coverage.shape[1]):

        axes[1, 2].plot(
            years,
            coverage[:, i],
            linewidth=2,
            label=f'Оператор {i+1}'
        )
    axes[1, 2].set_title('Покрытие 5G')
    axes[1, 2].set_xlabel('Год')
    axes[1, 2].set_ylabel('БС/км²')
    axes[1, 2].legend()
    axes[1, 2].grid(True)

    #CAPEX
    capex = np.array(self.history['CAPEX 5G'])
    for i, op in enumerate(self.operators):
        axes[2, 0].plot(
            years,
            capex[:, i],
            linewidth=2,
            label=op.name
        )
    axes[2, 0].set_title('CAPEX 5G')
    axes[2, 0].set_xlabel('Год')
    axes[2, 0].set_ylabel('CAPEX')
    axes[2, 0].legend()
    axes[2, 0].grid(True)

    #Проданные тарифы
    q_4g = np.array(self.history['Продано тарифов 4G'])
    q_5g = np.array(self.history['Продано тарифов 5G'])
    for i, op in enumerate(self.operators):
        axes[2, 1].plot(
            years,
            q_4g[:, i],
            linestyle='--',
            linewidth=2,
            label=f'{op.name} 4G'
        )
        axes[2, 1].plot(
            years,
            q_5g[:, i],
            linewidth=2,
            label=f'{op.name} 5G'
        )
    axes[2, 1].set_title('Проданные тарифы')
    axes[2, 1].set_xlabel('Год')
    axes[2, 1].set_ylabel('Количество')
    axes[2, 1].legend(fontsize=8)
    axes[2, 1].grid(True)

    #ARPU
    axes[2, 2].plot(
        years,
        self.history['ARPU 5G'],
        linewidth=2,
        marker='o'
    )
    axes[2, 2].set_title('ARPU 5G')
    axes[2, 2].set_xlabel('Год')
    axes[2, 2].set_ylabel('ARPU')
    axes[2, 2].grid(True)

    for ax_row in axes:
      for ax in ax_row:
        ax.xaxis.set_major_locator(
            MaxNLocator(integer=True)
        )
    plt.tight_layout()
    plt.show()