# -*- coding: utf-8 -*-
"""SUBSCRIBER

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1THpVI1ZsO13CIR1o_bQJgRCsVP0xNy4-
"""

import random
import numpy as np
import math

class Subscriber:
  def __init__(self, sub_id, beta = None, current_operator = None, current_tariff = None,
               willingness_to_pay = None, nu = None, switching_costs = None,
               is_rational = True, weight = 146000, best_u = None):
    self.id = sub_id
    if beta is None:
      beta = np.array([
        random.uniform(0.5, 1.5),
        random.uniform(3.0, 6.0),
        random.uniform(2.0, 5.0),
        random.uniform(1.0, 3.0),
        random.uniform(0.2, 1.0)
      ])
    self.beta = beta
    self.current_operator = current_operator
    self.current_tariff = current_tariff
    if willingness_to_pay is None:
      willingness_to_pay = random.uniform(50, 200)
    self.willingness_to_pay = willingness_to_pay
    if nu is None:
      nu = math.exp(random.gauss(mu = math.log(50), sigma = 0.8))
    self.nu = nu
    if switching_costs is None:
      switching_costs = random.uniform(30, 150)
    self.switching_costs = switching_costs
    self.is_rational = is_rational
    self.weight = weight
    self.best_u = best_u

  def update_willigness_to_pay(self):
    if self.current_tariff is not None:
      self.willingness_to_pay = (self.current_tariff.price + self.nu)
    else:
      self.willingness_to_pay = (random.uniform(50, 200) + self.nu)

  def utility(self, tariff, operator, price, speed, coverage, quality, ecosystem, speed_limit = None):
    speed = tariff.speed
    if speed_limit is not None:
      speed = min(speed, speed_limit)
    epsilon = np.random.gumbel(0, 1)
    u = self.beta[0]*(speed/1000) - self.beta[1]*(price/1000) + self.beta[2]*coverage * 100 + self.beta[3]*quality * 5 + self.beta[4]*ecosystem + epsilon
    return u

  def choose_tariff(self, available_tariffs, operators, speed_limit=None, current_year = 1):
    self.update_willigness_to_pay()
    adoption_rate = 1 / (1 + np.exp(-(current_year - 7) / 2))
    utilities = []
    tariffs = []
    for t in available_tariffs:
      if t.technology == '5G':
        if random.random() > adoption_rate:
          continue 
      operator = operators[t.operator_id]
      sc = 0
      if operator.id != self.current_operator.id:
        sc = self.switching_costs
      if not self.is_rational:
        if t.price > self.willingness_to_pay:
          continue
      V = self.utility(t, operator, t.price, t.speed, operator.coverage(), operator.quality, operator.ecosystem,
      speed_limit)
      V_adj = V - sc
      utilities.append(V_adj)
      tariffs.append(t)

    if len(tariffs) == 0:
      return self.current_tariff  

    exp_u = np.exp(utilities - np.max(utilities))
    probs = exp_u / np.sum(exp_u)
    chosen_idx = np.random.choice(range(len(tariffs)), p=probs)
    return tariffs[chosen_idx]